[package]
name = "tcpperf"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
pbr = "1.1.1"
tokio = { version = "1.43.1", features = ["net", "io-util", "rt-multi-thread", "macros"] }
