[package]
name = "tcpperf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
pbr = "1.1.1"
tokio = { version = "1.40.0", features = ["net", "io-util", "rt-multi-thread", "macros"] }

[dev-dependencies]
tokio-test = "0.4.4"
bytes = "1.6.1"
